//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignUpLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class TBLUserInfo
    {
        public int IDUs { get; set; }

        [Required(ErrorMessage = "VAZIO!")]
        [Display(Name = "Usuario")]

        public string UsernameUS { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "VAZIO!")]
        [Display(Name = "Senha")]
        public string PassWordUs { get; set; }

        [Required(ErrorMessage = "VAZIO!")]
        [Display(Name = "Confirmar Senha")]
        [DataType(DataType.Password)]
        [NotMapped]
        [System.ComponentModel.DataAnnotations.Compare("PassWordUs", ErrorMessage = "ERRO!")]
        public string rePassWordUs { get; set; }
    }
}
